safe: true
port: 4000
url:  http://localhost:4000

source:       .
destination:  ./_site
plugins_dir:  ./_plugins

future:       true
lsi:          false
highlighter:  rouge
markdown:     rdiscount
permalink:    pretty

rdiscount:
  extensions: [smart]

kramdown:
  auto_ids:       true,
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  enable_coderay: false
